### **Tensors**

Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters. They are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other specialized hardware to accelerate computing.

In [2]:
import torch
import numpy as np

#### **Tensor Initialization**

**From existing Data**

In [6]:
data = [[1., 2], [3, 4]]
x_data = torch.tensor(data)
print(x_data.dtype)
print(type(x_data))

torch.float32
<class 'torch.Tensor'>


**From a Numpy array**

In [7]:
np_array = np.array(data)
print(type(np_array))
x_np = torch.from_numpy(np_array) # can also be torch.tensor(np_array)
print(x_np)
print(type(x_np))

<class 'numpy.ndarray'>
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)
<class 'torch.Tensor'>


**From another tensor**

The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.

In [8]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overides the property (data type) of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1., 1.],
        [1., 1.]]) 

Random Tensor: 
 tensor([[0.7328, 0.6873],
        [0.1521, 0.9476]]) 



**From random or constant values**

In [35]:
torch.manual_seed(0) # initialize specific seed for reproducibility

shape = (2, 3)

# These operations automatically return floats as the data types
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


#### **Tensor Attributes**

They describe their shape, datatype, and the device on which they are stored.

In [11]:
tensor = torch.rand(2, 3)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([2, 3])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


#### **Tensor Operations**

In [12]:
import torch
print(torch.__version__)        # e.g., 2.0.1+cpu  ← means CPU-only build
print(torch.version.cuda)       # None if no CUDA support

2.5.1
None


In [13]:
# # We move our tensor to the GPU if available
# device = torch.accelerator.current_accelerator().type if torch.accelerator.is_available() else 'cpu'
# tensor = tensor.to(device)
# print(f"Device tensor is stored on: {tensor.device}")

Here’s a small sample of the mathematical operations available

In [40]:
r = (torch.rand(size=(2, 2)) - 0.5) * 2 # values between -1 and 1
print('A random matrix, r:')
print(r)

# Common mathematical operations are supported:
print('\nAbsolute value of r:')
print(torch.abs(r))

# ...as are trigonometric functions:
print('\nInverse sine of r:')
print(torch.asin(r))

# ...and linear algebra operations like determinant and singular value decomposition
print('\nDeterminant of r:')
print(torch.det(r))
print('\nSingular value decomposition of r:')
print(torch.svd(r))

# ...and statistical and aggregate operations:
print('\nAverage and standard deviation of r:')
print(torch.std_mean(r))
print('\nMaximum value of r:')
print(torch.max(r))

A random matrix, r:
tensor([[-0.4122,  0.0370],
        [ 0.3953,  0.6000]])

Absolute value of r:
tensor([[0.4122, 0.0370],
        [0.3953, 0.6000]])

Inverse sine of r:
tensor([[-0.4249,  0.0371],
        [ 0.4064,  0.6435]])

Determinant of r:
tensor(-0.2620)

Singular value decomposition of r:
torch.return_types.svd(
U=tensor([[-0.3355,  0.9420],
        [ 0.9420,  0.3355]]),
S=tensor([0.7526, 0.3481]),
V=tensor([[ 0.6786, -0.7345],
        [ 0.7345,  0.6786]]))

Average and standard deviation of r:
(tensor(0.4440), tensor(0.1550))

Maximum value of r:
tensor(0.6000)


**Standard numpy-like indexing and slicing**

In [14]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**Joining tensors**

In [15]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


**Multiplying tensors**

In [16]:
print(tensor.mul(tensor), "\n") # This computes the element-wise product
# Alternative syntax
print(tensor * tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [17]:
print(tensor.matmul(tensor), "\n") # This computes the matrix multiplication between two tensors
# Alternative syntax
print(tensor @ tensor)

tensor([[3., 0., 3., 3.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.]]) 

tensor([[3., 0., 3., 3.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.]])


**In place operations**

Operations that have a `_` suffix are in-place.

In [20]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


#### **Bridge with Numpy**

Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other.

**Tensor to Numpy array**

In [21]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}, {type(n)}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.], <class 'numpy.ndarray'>


A change in the tensor reflects in the NumPy array.

In [22]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


**Numpy array to Tensor**

In [23]:
n = np.ones(5)
t = torch.from_numpy(n)

Changes in the NumPy array also reflects in the tensor.

In [27]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
